services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: local
      - key: APP_KEY
        value: base64:8AGpZijCGGkypEiK8AjW9PSH5xJVHOkR8q2cKi5+/PY=
      - key: APP_DEBUG
        value: 'true'
      - key: APP_URL
        value: https://laravel-app.onrender.com
      - key: LOG_CHANNEL
        value: stack

      # --- PostgreSQL Settings ---
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-db
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-db

    startCommand: |
      php artisan config:cache && \
      php artisan migrate --force && \
      apache2-foreground

databases:
  - name: laravel-db
    databaseName: db_songchord
    user: laraveluser   # nama user bisa kamu tentukan, jangan 'root'
    ipAllowList: []     # allow internal only
